* Susanna Romanus [2026-09-02]

** Upplägg: Prata med flera i branschen och förhoppningsvis hitta painpoints.


** Från inkommet manus till bok i handen på en läsare.


** anteckningar

digital utgivning är typ bara ljudböcker.

ljud kan vara 50% och e max 10%.



** Kedja

hoppas på att manus kommer

*** Manus kommer i digtal inbox. Skräddarsytt för Bonnier.

Där manus sorteras in och kategoriseras.
Skickas digitalt till lektör.
Skickas tillbaka till redaktör.

Kan man utröna om det finns sådana system ute idag hos småförlag.


Merparten för ett standardnej.

1000 manus om året.

Det lätta är att bli av ointrassnta.

Det som tar tid är "det här kan va nåt".

Lektörsutlåtanden viktiga.

Manus från agenter.

Manus från folk de känner.

Manus från pågående författarskap.


*** Om man hittar ett bra manus läses det av Susanna eller Åsa

Hamnar i Bonniers affärssystem för.



*** Redaktörsarbete är efter antagninsbesked.

Mejlar wordversioner fram och tillbaka.

Omvandlar till PDF och läser på läsplatta.

Redaktörerna nöjda med.

Red sätter manus själva i indesign.

Fördigt manus i Indesign.

Concept till Work

Omslags. Allt detta "publiceras" till Bokinfo.


"Ännu ej utgiven" tex.

Tryck och Inläsning och produktion av epub-fil.

Bonnier Audio - producent av ljudbok.

Många kostnader före intäkt för bok.

Huvudsak svensk skönlitteratur. Spänning och feel good. Litterära böcker. 2-3 fackböcker.


Ljudbok väldigt dyrt att göra. Allt blir inte ljudbok.

AI - Finns redan hos Storytel.
Lyssnaren kan välja i Storytel / Bookbeat / Nextory
Storytel original.

AI översättning.


AI i stöd för lektörs.


Marknadsföring / PR inga recensioner.

Hur skall man skapa synlighet när det.

Performance marketing.
Annonser i sociala medier mm.
Olika ÅF.

Mycket AI-filmer.


Finns ett team som mäter och testar performance marketing.

Föfattarportalen.

Storytel puls. Författare kan se en massa om lyssning för deras titlar.

** Volante

** Martin Kaunitz Tomas Olsson,
SKönlitt + serier

** Mondial

** Fri Tanke
Christer Sturmark

** Bookmark
oberoende

** 
