* Arianna Bommarco [2026-10-06]

** Upplägg: Prata med flera i branschen och förhoppningsvis hitta painpoints.

** Från inkommet manus till bok i handen på en läsare.

**
Manus kommer in på olika sätt.

Manusinkorgen. Inte mycket som hämtas där.

Agenter.

Uppsökande.

När man väl har ett projekt som känns lovande. Tar man det till redaktionen.

Antingen

Förläggare har man idéer om vad man vill ha in.

"Är du indrivare"

Pitchar idéer till,

Bonniers går till AKP,

Omvärldsbevakning, generellt,

Källor för omvärldsbevakning.

Kanske scannar good reads, går på mässor, träffar agenter, utländska systerförlag, skannar topplistor i andra länder.

Johanna Kink, enpersonsförlag,

Färskt vatten till blommorna.

Bokscouter.

AB skulle kunna scouta till andra länder.


Bokmässan i Frankfurt pågår nu.

Nuanxed - tjänst som är helhetslösning

Gör AI-översättning, redigerar, korrar, får tillbaka ett perfekt manus.

Blir inte billigare men mycket enklare.

Jonas Thelander, Storytel-grundare, Goread. Riktar sig till vem som helst som
vill ge ut en bok.

Redan nu en överutgivning som är helt.

Tror att den ekonomiska strategin

Bookmark - spetsiga utgivning - högprofilerade.

Författaridentiteten viktig för författarna. Hur man når ut medialt.

Men hos tex Storytel, där kan helt okända sälja jättemycket.

Man kan vara stor i ljud och inte i print.

Adlibris startar ny butik på drottninggatan efter jul.


Förlagen slår rekord i hur mycket de säljer.

Yngre generationen vill läsa på papper.

Folk köper SÅ mycket böcker på engelska. Ökande.

Det som trendar på TikTok. Ungdomarna vill ha det på originalspråk.

Går inte att överblicka BookTok.

Ljudboksbranschen är unik i sverige att vi har strömningstjänster.

Penguin tex låter inte böcker finnas på strömningstjänster.

Storytel har försökt.

Nu växer det dock i Polen.

Många ljudbokstjänster. Ett problem är att samla data och Royalty från alla
tjänster. Väldigt splittrat. Många plattformar.

Nextory går upp i Bookbeat. Dvs bara två tjänster kvar i Sverige och närmar sig därmet Storytel.

Våta drömmen för ljudbokstjänster

Audible dominerar i tyskland.

Finland är enda som slår sverige i ljudbokslyssning.

Nästan all genrelitt på ljud.

Två prod-kostnader.


Korrekturlyssnas efterråt.

Processen för pappersboksutgivning ganska överblickbar.
Papper + ljud + ebok.

Mycket mer admin idag.

Redchef har överblick.
några förläggare.
redaktörer.

form nästan alltid frilans.

Mycket planering kring produktionen. Sjumiljoner deadlines för olika grejer.

Har inte mycket kontrollbehov.

Redaktör och författare jobbar igenom manus.

Red-arb slitigt.

Önskat att det att funnits.

Jobbar i Word.

Jävla massa flikar och en massa flikar till som man inte vet vad det är till för.

Om någon har gjort ett indrag som ligger fel. Måste typ gå en word-kurs.

Många skriver i Scrivener, mm.

Jobbar jättemycket i Word

Ta bort alla dubbla punkter tex.

Grov redigering.

Godkänna eller avslå.

Vissa jobbar med Google docs.

Man vill väldigt noggrant kunna spår ändringar.

Redigeringsbiten är rätt tung.

Upprepningar, även

Författare skriver samma sak tre gånger.

Beskriver något som hänt i boken. Upprepningar av saker som läsaren redan vet.

Serier. Ville anställa någon som håller koll och gör en karaktärsbibel.

Det AI berättade om texten var inte bra.

Väldigt generiska svar.

Det litterära tillåts ta tid.


Formaten konkurrear inte med varandra.

ljudboken har slagit ut deckare och ljudbok.

Förtroendebransh, kontakter och nätverk. Finns inga digitala genvägar i det.

OM DET FANNS ETT SÄTT ATT SKANNA EN MARKNAD.

Men man skulle ändå ligga ett steg efter.

Manusinkorgen.

Vissa förlag måste ha väldigt bra koll på sin manusinkorg.

Andra förlag kollar förmodligen inte.

Men jag tror att Bonniers har rätt bra koll.


Manusinkorgen är spännande.

Man skulle vilja ha genre, ålder på författare, publicerad tidigare.
Blir bättre och bättre på att identifiera vad som skall rensas bort.

Kanske Sortering på genre.

Folk skickar Word/PDF. Hos många är det formaliserat.

Manusinkorgen inte betungande.

Excellistorna, Trello,

Utgivningslistor, Vårlista, höstlista.

Stora förlag har workflow-program som är specialdesignade.

Det är många som är inne i samma proj

marknad, säljare, redaktör,

Folk måste uppdatera för det skall funka.


Redaktionsmöte en gång i veckan där man pratar igenom allt som pågår.

Utgivningsmöte, pitchar idéer, förläggare, marknad. Pratar innehåll.

Arbete är olika organiserat.

Processen.

Förläggarläsning, redaktörsvändor

Mycket samordning av projekten.

Förläggaren, redaktör, formgivare, sättare, admin som lägger upp i alla digitala system,

Distributörstjänst som är dålig. We Do Books? Tidigare enda distributör till Elib, Axiell var hopplösa. Publizon.
Bokus, Adlibris, Audible, Bokus Play.

Distribution.

Tror att man skall prata med folk som är högre upp.

Redaktionschefer eller förlagschefer. Har en vision framåt.
Som kanske förstår var man har mycket kostnader.

Hos dem deras VD.

Har precis köpts till 80% av Storytel.

Överblicka större struktur och detaljer.

Ett nytt word att jobba i.

Författarna skulle vilja fortsätta jobba i Scriviner,

Svensk bokhandel, mycket är låst.

Koll på de digitala formaten.

Ljudboken är stått mot eboken.

Tror att kobo ökar lite ändå.

Frontlist och Backlist.
